# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9b10f8e35e8a6940ed50bbef56058201f10c4e05f142a6602aa6aa4fa66050f42181a9bd3f57994a69a4c4785f5c4ed3a67103b52270b337518d65c9903b8d2

test:
  secret_key_base: 2df05e6623253a81ab3f5497bef40fa83d10e12d37e7e16eb7d1fe19c4f89bae4e8fd9c38ee31fd1bafa7f2070cb1e2d1ab035ae39a6816cb0f4d313e71d2100

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
